# about dein hooks
# Junp to link by 'Leader + b'
# https://qiita.com/delphinus/items/cd221a450fd23506e81a

##################
# init
##################
[[plugins]]
repo = '~/.cache/dein/repos/github.com/Shougo/dein.vim'

##################
# colorschemes
##################
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
'''

##################
# outline-desplay
##################
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#branch#enabled = 1
  " see this site: https://github.com/vim-airline/vim-airline/wiki/Screenshots
  let g:airline_theme = 'kalisi'
'''

[[plugins]] # show indent line
repo = 'Yggdroot/indentLine'

####################################
# language specific plugins bellow
####################################

##################
# ruby
##################
[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = ['ruby', 'eruby', 'haml','slim','erb']
depends = ['neocomplete.vim','vimproc.vim']

hook_add = '''
  let g:monster#completion#backend = "solargraph"
  " let g:monster#completion#rcodetools#backend = "async_rct_complete"
  " Set async completion.
  let g:monster#completion#rcodetools#backend = "async_solargraph_complete"
  " let g:monster#completion#rcodetools#backend = "async_rct_complete"
" autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
  if !exists('g:neocomplete#force_omni_input_patterns')
   let g:neocomplete#force_omni_input_patterns = {}
  endif
  let g:neocomplete#force_omni_input_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'

'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'Townk/vim-autoclose'
on_ft = ['ruby']

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = ['ruby']

[[plugins]]
repo = 'ngmy/vim-rubocop'
on_ft = ['ruby']
hook_add = '''
let g:syntastic_ruby_rubocop_exe = 'rbenv exec bundle exec rubocop'
let g:vimrubocop_rubocop_cmd = 'rbenv exec bundle exec rubocop'
" let g:vimrubocop_config = ''
'''

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']


[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

##################
# csv
##################
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['fish']

##################
# markdown
##################
# [[plugins]] # a little heavy for my environment
# repo = 'plasticboy/vim-markdown'
# on_ft = ['markdown','md']

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['markdown','md']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['uml']

[[plugins]]
repo = 'tenfyzhong/tagbar-markdown.vim'
on_ft = ['markdown', 'md']

##################
# javascript
##################
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']


##################
# vue
##################
[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','vue']


##################
# elm
##################
[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = ['elm']


##################
# kotlin
##################
[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

##################
# graphql
##################
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['gql', 'graphql', 'Relay.QL']

##################
# toml
##################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml', 'tml']

[[plugins]] # contextのファイルタイプを判定する
repo = 'Shougo/context_filetype.vim' # 依存関係
on_ft = ['toml', 'tml', 'md']

[[plugins]] # コンテキストが違ったときに、シンタックスを変えられる
repo = 'osyo-manga/vim-precious'
on_ft = ['toml', 'tml']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

