#!/bin/sh
sgrm() {

  # files=$(git status --short | awk '{print $2}') &&
  files=$(git ls-files)
  selected_files=$(echo "$files" | fzf -m --preview 'git diff {}') &&
  git rm $selected_files
}

sgrm
