#!/usr/bin/env ruby

# # command line
refname = ARGV[0]

class String
  def to_snake
    self
      .gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
      .gsub(/([a-z\d])([A-Z])/, '\1_\2')
      .tr("-", "_")
      .downcase
  end
end

puts "check spell:"

`which aaspell`
if $?.exitstatus  == 1
  puts <<-EOS

    `aspell` is not insalled!

    please exec bellow and install it.

    `brew install aspell`

  EOS
 exit 1
end

# commit_msg = File.read(refname).to_snake.gsub('_', ' ')
commit_msg = refname.to_snake.gsub('_', ' ') # for debug

stdout = `echo #{commit_msg} | aspell list --lang=en`


if stdout.length > 0
    puts "  may be misspelled words:"
    stdout
      .split("\n")
      .each.with_index(1) {|miss_spell,index| puts "#{index} #{miss_spell}" }
    exit 1
end

puts "  success checking spell!"

exit 0
